version: '3'
services:
  go:
    container_name: go
    build:
      context: .
      dockerfile: ./go/Dockerfile
    volumes:
      - ./migrations:/go
    tty: true
    # env_file: # .envファイル
    #   - ./go/.go_env
    environment:
      - TZ=Asia/Tokyo
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - MYSQL_HOST=[db]
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=develop
  db:
    container_name: db
    image: mysql:5.7.29
    restart: always
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=develop

